name: Staging Deployment

on:
  push:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: git-ftp-action
      uses: sebastianpopp/git-ftp-action@2.1.0
      with:
        # URL
        url: "${{ secrets.FTP_SERVER}}/${{ secrets.STAGING_FTP_DIR}}/"
        # FTP login name
        user: "${{ secrets.FTP_USERNAME }}"
        # FTP password
        password: "${{ secrets.FTP_PASSWORD }}"