name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: '0'

    - name: Setup Hugo
      uses: peaceiris/actions-hugo@v3
      with:
        hugo-version: '0.143.0'
        extended: true

    - name: Build Hugo
      run: |
        hugo build --config hugo.toml

    - name: git-ftp-action
      uses: sebastianpopp/git-ftp-action@3.0.0
      with:
        # URL
        url: "${{ secrets.FTP_SERVER}}/${{ secrets.FTP_DIR}}/"
        syncroot: ./public
        # FTP login name
        user: "${{ secrets.FTP_USERNAME }}"
        # FTP password
        password: "${{ secrets.FTP_PASSWORD }}"